[package]
name = "mmap-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
gl = "0.14.0"
imgui = "0.8.2"
imgui-sdl2 = "0.15.0"
imgui-opengl-renderer = "0.11.1"
